---
- name: Install Applications from Homebrew
  homebrew:
    name: '{{ item }}'
    options: force
  loop:
    - python@3
  become: false

- name: Install Applications from Homebrew Cask
  homebrew_cask:
    name: '{{ item }}'
    options: force
  loop:
    - iterm2
    - slack
    - google-chrome
    - firefox
    - tunnelblick
    - authy
  become: false
