---
- name: Install Applications from Homebrew
  homebrew:
    name: '{{ item }}'
    options: force
  loop:
    - python@3

- name: Install Applications from Homebrew Cask
  community.general.homebrew_cask:
    name: '{{ item }}'
    options: force
  loop:
    - iterm2
    - slack
    - google-chrome
    - firefox
    - authy
